project_id = "uojmvqkuyqkskbsxypji"

[functions.book-ai]
verify_jwt = false

[functions.book-chat]
verify_jwt = false

[functions.word-import]
verify_jwt = true

[functions.book-publish]
verify_jwt = true
