project_id = "uojmvqkuyqkskbsxypji"

[functions.book-ai]
verify_jwt = false

[functions.book-suggest]
verify_jwt = false

[functions.book-chat]
verify_jwt = false

[functions.word-import]
verify_jwt = false

[functions.book-publish]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.seed-test-users]
verify_jwt = false

[functions.book-image-gen]
verify_jwt = true

